Object manipulation 3
annaaksenov/m1-0323-code-solutions pull request #69
Opened 2023-06-27 00:20 UTC by annaaksenov

object-manipulation-3 - Anna Ak.

2023-07-17 06:04 UTC, kurtyazdizadeh requested changes

2023-07-17 06:04 UTC, kurtyazdizadeh commented on object-manipulation-3/main.js
> +// push? the deck into 'hand' arrays... for...in loop?
to deal cards to the player, you can take the shuffled array of cards and either use other lodash array methods like `_first` or a native javascript array method like `splice`

2023-08-04 02:15 UTC, TimelikeClosure requested changes

2023-08-04 02:15 UTC, TimelikeClosure commented on object-manipulation-3/main.js
> +}
It seems like your `shuffleDeck` function is attempting to do more that just shuffling the deck. I suggest only trying to deal cards from the `deal` function.

2023-08-04 02:15 UTC, TimelikeClosure commented on object-manipulation-3/main.js
> +}
I suggest having your `deal` function take two parameters: the deck, and the players.

2023-08-07 00:24 UTC, kurtyazdizadeh approved these changes
Looks like it works! Nice job, approved 👍

2023-08-07 20:51 UTC, merged